version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing Serverless plugins
      - npm run install:all
      - npm run build:all
      - npm run test
  build:
    commands:
      - serverless deploy --stage ${STAGE_NAME}

cache:
  paths:
    - node_modules